global:
  scrape_interval: 10s
  evaluation_interval: 10s
  external_labels:
    app: orchestrix-gateway

scrape_configs:
  - job_name: orchestrix-gateway
    metrics_path: /metrics
    static_configs:
      - targets: ["api:8000"]
